# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: brume
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: scrapofy
# "service" is the name of this project. This will also be added to your AWS resource names.
service: getTracks

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*